# Generated by Django 5.0.4 on 2024-05-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('oder_status', models.CharField(choices=[('PENDING', 'pending'), ('DELIVER', 'deliver'), ('SHIPPED', 'shipped')], max_length=50)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('current_stock', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='items.orders')),
            ],
        ),
    ]
